package com.myspace.drug_orders.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Street")
	private java.lang.String street;
	@org.kie.api.definition.type.Label("ZIP Code")
	private java.lang.String zipCode;
	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label(value = "City")
	private java.lang.String city;

	public Address() {
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.String zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public Address(java.lang.String street, java.lang.String zipCode,
			java.lang.String state, java.lang.String country,
			java.lang.String city) {
		this.street = street;
		this.zipCode = zipCode;
		this.state = state;
		this.country = country;
		this.city = city;
	}

}
