package com.myspace.drug_orders.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Clinic implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Address")
	private com.myspace.drug_orders.model.Address address;

	public Clinic() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public com.myspace.drug_orders.model.Address getAddress() {
		return this.address;
	}

	public void setAddress(com.myspace.drug_orders.model.Address address) {
		this.address = address;
	}

	public Clinic(java.lang.String name,
			com.myspace.drug_orders.model.Address address) {
		this.name = name;
		this.address = address;
	}

}
