package com.myspace.drug_orders.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class DrugStock implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("SKU Number")
	private java.lang.String skuNo;
	@org.kie.api.definition.type.Label("Expired")
	private java.lang.Boolean expired;

	@org.kie.api.definition.type.Label("In Stock")
	private java.lang.Boolean inStock;

	@org.kie.api.definition.type.Label(value = "Inventory Reservation No")
	private java.lang.String inventoryReservationNo;

	public DrugStock() {
	}

	public java.lang.String getSkuNo() {
		return this.skuNo;
	}

	public void setSkuNo(java.lang.String skuNo) {
		this.skuNo = skuNo;
	}

	public java.lang.Boolean getExpired() {
		return this.expired;
	}

	public void setExpired(java.lang.Boolean expired) {
		this.expired = expired;
	}

	public java.lang.Boolean getInStock() {
		return this.inStock;
	}

	public void setInStock(java.lang.Boolean inStock) {
		this.inStock = inStock;
	}

	public java.lang.String getInventoryReservationNo() {
		return this.inventoryReservationNo;
	}

	public void setInventoryReservationNo(
			java.lang.String inventoryReservationNo) {
		this.inventoryReservationNo = inventoryReservationNo;
	}

	public DrugStock(java.lang.String skuNo, java.lang.Boolean expired,
			java.lang.Boolean inStock, java.lang.String inventoryReservationNo) {
		this.skuNo = skuNo;
		this.expired = expired;
		this.inStock = inStock;
		this.inventoryReservationNo = inventoryReservationNo;
	}

}
