package com.myspace.drug_orders.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Drug implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("SKU Number")
	private java.lang.String skuNo;
	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Unit Price")
	private java.math.BigDecimal unitPrice;

	public Drug() {
	}

	public java.lang.String getSkuNo() {
		return this.skuNo;
	}

	public void setSkuNo(java.lang.String skuNo) {
		this.skuNo = skuNo;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.math.BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(java.math.BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Drug(java.lang.String skuNo, java.lang.String type,
			java.lang.String description, java.math.BigDecimal unitPrice) {
		this.skuNo = skuNo;
		this.type = type;
		this.description = description;
		this.unitPrice = unitPrice;
	}

}
