package com.myspace.drug_orders.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OrderLineItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Drug")
	private com.myspace.drug_orders.model.Drug drug;
	@org.kie.api.definition.type.Label("Quantity")
	private int quantity;
	@org.kie.api.definition.type.Label("Shipping Address")
	private com.myspace.drug_orders.model.Address shippingAddress;

	@org.kie.api.definition.type.Label("Shipped")
	private boolean shipped;

	public OrderLineItem() {
	}

	public com.myspace.drug_orders.model.Drug getDrug() {
		return this.drug;
	}

	public void setDrug(com.myspace.drug_orders.model.Drug drug) {
		this.drug = drug;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public com.myspace.drug_orders.model.Address getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(
			com.myspace.drug_orders.model.Address shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	public boolean isShipped() {
		return this.shipped;
	}

	public void setShipped(boolean shipped) {
		this.shipped = shipped;
	}

	public OrderLineItem(com.myspace.drug_orders.model.Drug drug, int quantity,
			com.myspace.drug_orders.model.Address shippingAddress,
			boolean shipped) {
		this.drug = drug;
		this.quantity = quantity;
		this.shippingAddress = shippingAddress;
		this.shipped = shipped;
	}

}
