package com.myspace.drug_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Clinic implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Clinic() {
    }




}