package com.myspace.drug_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Doctor implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Doctor() {
    }




}