package com.myspace.drug_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Drug")
	private com.myspace.drug_orders.Drug drug;
	@org.kie.api.definition.type.Label("Quantity")
	private int quantity;
	@org.kie.api.definition.type.Label("Shipping Address")
	private com.myspace.drug_orders.Address shippingAddress;

	@org.kie.api.definition.type.Label(value = "Shipped")
	private boolean shipped;

	public OrderItem() {
	}

	public com.myspace.drug_orders.Drug getDrug() {
		return this.drug;
	}

	public void setDrug(com.myspace.drug_orders.Drug drug) {
		this.drug = drug;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public com.myspace.drug_orders.Address getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(
			com.myspace.drug_orders.Address shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	public boolean isShipped() {
		return this.shipped;
	}

	public void setShipped(boolean shipped) {
		this.shipped = shipped;
	}

	public OrderItem(com.myspace.drug_orders.Drug drug, int quantity,
			com.myspace.drug_orders.Address shippingAddress, boolean shipped) {
		this.drug = drug;
		this.quantity = quantity;
		this.shippingAddress = shippingAddress;
		this.shipped = shipped;
	}

}