package com.myspace.drug_orders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Order Items")
	private java.util.List<com.myspace.drug_orders.OrderItem> orderItems;

	public Order() {
	}

	public java.util.List<com.myspace.drug_orders.OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(
			java.util.List<com.myspace.drug_orders.OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public Order(java.util.List<com.myspace.drug_orders.OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}